ALTER TABLE agent_configs
  ADD COLUMN IF NOT EXISTS first_name TEXT,
  ADD COLUMN IF NOT EXISTS last_name TEXT,
  ADD COLUMN IF NOT EXISTS company TEXT,
  ADD COLUMN IF NOT EXISTS role TEXT,
  ADD COLUMN IF NOT EXISTS industry TEXT,
  ADD COLUMN IF NOT EXISTS pain_points TEXT,
  ADD COLUMN IF NOT EXISTS hook_style TEXT,
  ADD COLUMN IF NOT EXISTS follow_up_cadence TEXT,
  ADD COLUMN IF NOT EXISTS icp_target_industries TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS meeting_target INTEGER NOT NULL DEFAULT 15,
  ADD COLUMN IF NOT EXISTS deal_size TEXT,
  ADD COLUMN IF NOT EXISTS sales_cycle TEXT,
  ADD COLUMN IF NOT EXISTS tools TEXT[] NOT NULL DEFAULT '{}';
