-- Add missing onboarding columns to agent_configs
ALTER TABLE agent_configs
  ADD COLUMN IF NOT EXISTS first_name TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS last_name TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS company TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS role TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS industry TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS pain_points TEXT,
  ADD COLUMN IF NOT EXISTS hook_style TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS icp_target_industries TEXT[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS meeting_target INTEGER DEFAULT 15,
  ADD COLUMN IF NOT EXISTS deal_size TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS sales_cycle TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS follow_up_cadence TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS tools TEXT[] DEFAULT '{}';
